apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-diabetes
spec:
  replicas: 2
  selector:
    matchLabels:
      name: frontend-diabetes
  template:
    metadata:
      labels:
        name: frontend-diabetes
    spec:
      containers:
        - name: frontend-diabetes
          image: rishabhsaradigi/frontend-diabetes:latest
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80