name: check the code and verify

on: 
  push: 
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
  
    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: verify checkout
        run: echo "Code checked successfully on ${{ matrix.os }} operating system."

